### ISSUE TITLE
Program unable to crawl series with nonstandard chapter numbers

### ISSUE THREAD

**Issue by gyratory** [klaxa/batotocrawler#8]
Hi,
I was attempting to download the series "KURO" from both batoto and kissmanga but due to the weird numbering conventions (e.g. each release is numbered "Ch. 1-18", "Ch. 19-50", etc...) the crawler fails to scrape the chapters from the series page.
traceback for both batoto and kissmanga:
```
gyratory@005:~/batotocrawler$ python3.4 ./Manager.py -d ~/downloads/kuro --cbz --interactive http://bato.to/comic/_/comics/kuro-r11140
Traceback (most recent call last):
  File "./Manager.py", line 240, in <module>
    duplicate_chapters(chapters)
  File "./Manager.py", line 102, in duplicate_chapters
    interactive()
  File "./Manager.py", line 69, in interactive
    print_initial()
  File "./Manager.py", line 35, in print_initial
    print_info("{} releases for chapter {:g}: ".format(number_of_releases, duplicates[0]["chapter"]), newline=False)
ValueError: Unknown format code 'g' for object of type 'str'
```
```
gyratory@005:~/batotocrawler$ python3.4 ./Manager.py -d ~/downloads/kuro --cbz --interactive http://kissmanga.com/Manga/KURO
Traceback (most recent call last):
  File "./Manager.py", line 201, in <module>
    chapters = manga.series_chapters()[::-1]
  File "/home/gyratory/downloads/batotocrawler/Scrapers/KissManga.py", line 130, in series_chapters
    chapters.append(self.chapter_info(chapter))
  File "/home/gyratory/downloads/batotocrawler/Scrapers/KissManga.py", line 42, in chapter_info
    chapter_number = re.search(r'{} .* ([0-9\.]*) -.*'.format(self.series_info('title')), chapter.a.text).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
```

**Comment by Hamuko** [comment]
Please test the `nonstandard-chapter-fi` branch.

I changed the regex that matches the chapter numbers on KissManga, but due to the **extremely** random way that they organize the chapters, it's pretty volatile and will probably still crash on a lot of cases. That's why a sensible site like Batoto is preferable in most cases.

**Comment by gyratory** [comment]
The new branch worked for both batoto and kissmanga.
However when I tested using `--interactive` there was a problem scraping from batoto:
```
gyratory@005:~/downloads/batotocrawler-chfix$ python3.4 ./Manager.py -d ~/downloads/kuro --cbz --interactive http://bato.to/comic/_/comics/kuro-r11140
Five releases for chapter Extra: Boon Scanlation, Boon Scanlation, Boon Scanlation, Boon Scanlation, Boon Scanlation.
1. Boon Scanlation
2. Boon Scanlation
3. Boon Scanlation
4. Boon Scanlation
5. Boon Scanlation
>> 1
Invalid input.
>> 2
Invalid input.
>> 3
Invalid input.
>> 4
Invalid input.
>> 5
Invalid input.
>> ^Z
[1]+  Stopped                 python3.4 ./Manager.py -d ~/downloads/kuro --cbz --interactive http://bato.to/comic/_/comics/kuro-r11140
```

**Comment by Hamuko** [comment]
Try the latest commit.

**Comment by gyratory** [comment]
There appears to be no problems with the latest commit.  I was able to select any of the given options and begin scraping.  Thanks for the prompt response and hard work!
